### ISSUE TITLE
Understanding "UnSample" function

### ISSUE THREAD

**Issue by fjricci** [GoogleCloudPlatform/cloud-profiler-java#22]
I'm trying to understand how the following function works (I know something similar exists in pprof as well, so I'm not claiming that it's broken).

https://github.com/GoogleCloudPlatform/cloud-profiler-java/blob/6e228f34627542c4c8dc49db6fbe30653fc02144/third_party/javaprofiler/profile_proto_builder.cc#L77-L90

My understanding is that if I have 2 stack traces that allocate things, stack A with a big allocation and stack B with a small allocation, I need to use a multiplication factor to account for the fact that the allocation profiler's sampling rate is more likely to hit stack A than stack B on a given sample. This makes sense to me.

I have another understanding that the total bytes allocated by a stack is equal to:
`TotalAllocatedSize = count * size`
So to compare the quantity of stuff allocated by stack A and stack B, I'd want to multiply `count` and `size` for the 2, and then compare. If the total for stack A is double the total for stack B, we can assume stack A is allocating about twice as much data as stack B.

Where I get confused is when these two things are combined. If the multiplication factor is supposed to account for how much more likely large allocations are to be seen than small allocations, it seems like the new "adjusted" total should be: `TotalAllocatedSize = count * size * factor`
However, given that both `count` and `size` are getting modified, the actual result we'll get is:
`TotalAllocatedSize = (count * factor) * (size * factor)`
This ends up pulling in the factor twice, which seems like double-counting to me. Am I missing something here?

Let's look at some concrete numbers here for stack A and stack B.
```
Sample Rate: 1MB
Allocation A: 1KB
Allocation B: 10KB
Sampling Factor A: 1000
Sampling Factor B: 100
```
Let's say we see 1 of stack A and 1 of stack B.
```
AdjustedCount A: 1 * 1000 = 1000
AdjustedCount B: 1 * 100 = 100
AdjustedSize A: 1KB * 1000 = 1MB
AdjustedSize B: 10KB * 100 = 1MB
```
This means that the total *adjusted* size allocated by A and B would be:
```
TotalAdjustedSize A: 1000 * 1MB = 1GB
TotalAdjustedSize B: 100 * 1MB = 100MB
```
 Intuitively, I'd expect that the total allocations from the 2 stacks are the same. We're 10x as likely to see an allocation from stack B, so a stack from A should count 10x as much, and therefore 1 of each would cancel out. Instead we see the total from A is 10x the total from B. Does this make sense statistically? Is there some documentation for where the formula came from?

**Comment by aalexand** [comment]
`sample->set_value(kMetric, static_cast<double>(metric_value) * ratio);` is the total allocated bytes, not individual allocation size. kMetric / kCount is the allocation size, both before and after unsampling (since scaled by the same factor).

Please re-open if this doesn't answer your question.
