### ISSUE TITLE
Profile is created but nothing shows on GCP Profiler Dashboard

### ISSUE THREAD

**Issue by poulad** [GoogleCloudPlatform/cloud-profiler-java#38]
Hi. I am trying to instrument Cloud Profiler for my Spring Boot web app running in a GKE cluster. According to the logs, the profiling information is sent correctly but I can't figure out why no profiling data is shown on Cloud Profiler dashboard at
https://console.cloud.google.com/profiler?project=MY_PROJECT

```dockerfile
FROM jetty:9.4.42-jdk11

ADD app.war $JETTY_BASE/webapps/ROOT.war

USER root

ENV JAVA_TOOL_OPTIONS="${JAVA_TOOL_OPTIONS} -agentpath:/opt/cprof/profiler_java_agent.so=-logtostderr,-minloglevel=0,-cprof_enable_heap_sampling=true,-cprof_project_id=MY_PROJECT,-cprof_service=MY_SERVICE,-cprof_service_version=0.0.1,-cprof_zone_name=us-central1-c"

RUN set -x \
  && mkdir -p /opt/cprof \
  && wget -q -O- "https://storage.googleapis.com/cloud-profiler/java/latest/profiler_java_agent.tar.gz" \
    | tar xzv -C /opt/cprof

USER jetty
```

Logs at startup:
```
Picked up JAVA_TOOL_OPTIONS:  -agentpath:/opt/cprof/profiler_java_agent.so=-logtostderr,-minloglevel=0,-cprof_enable_heap_sampling=true,-cprof_project_id=MY_PROJECT,-cprof_service=MY_SERVICE,-cprof_service_version=0.0.1,-cprof_zone_name=us-central1-c
I0621 22:59:35.883452    37 entry.cc:272] Google Cloud Profiler Java agent version: cloud-profiler-java-agent_20210621_RC00
I0621 22:59:35.883504    37 entry.cc:274] Profiler agent loaded
I0621 22:59:35.883514    37 entry.cc:157] Prepare JVMTI
I0621 22:59:35.929713    37 entry.cc:111] On VM init
I0621 22:59:35.931141    37 worker.cc:78] Java version: 11.0.11
I0621 22:59:35.931180    37 worker.cc:82] Heap allocation sampling supported for this JDK
I0621 22:59:35.931186    37 cloud_env.cc:129] Using project ID 'MY_PROJECT' from flags
I0621 22:59:35.931188    37 cloud_env.cc:143] Using zone name 'us-central1-c' from flags
I0621 22:59:35.931538    37 throttler_api.cc:280] Will use profiler service cloudprofiler.googleapis.com to create and upload profiles
I0621 22:59:35.935149    55 throttler_api.cc:206] Initialized deployment: project_id=MY_PROJECT, service=MY_SERVICE, service_version=0.0.1, zone_name=us-central1-c
I0621 22:59:35.935186    55 throttler_api.cc:304] Creating a new profile via profiler service
I0621 22:59:38.750341    55 throttler_api.cc:318] Profile created: cpu projects/MY_PROJECT/profiles/1d2b85d5c0985dcb

(there are many more logs like this about uploading and creating profiles successfully)
```

I have double checked using the correct actual values for `MY_PROJECT` and `MY_SERVICE`. I am using the default 7 days timespan up to NOW on the dashboard. It's been close to 12 hours since the first profiles were uploaded. Issue is the same whether I run this container locally on my Mac or in the GKE environment.

The default message I see on Profiler dashboard is:
```
No profiling data is found for project "MY_PROJECT", likely because no profiling agent has been configured or the timespan selected includes no profiles.
```

**Comment by aalexand** [comment]
Do you really use `MY_PROJECT` and `MY_SERVICE` or are these placeholders? These are supposed to be lowercase.

**Comment by poulad** [comment]
those are placeholders. actual names are like project `foo0bar` and service `baz-gateway`

**Comment by aalexand** [comment]
If there are log messages that the profiles were uploaded successfully then it's pretty weird they don't show up. Some very naive theories would be: 1) check that you are using the same project ID in the UI (note that project name != project ID != project number); 2) check that you reloaded / refreshed the UI...

**Comment by poulad** [comment]
I double checked that too. My project's Name and ID are the same (e.g. `foo0bar`)

**Comment by poulad** [comment]
This is another confirmation that a lot of profiles have been created so far.

https://console.cloud.google.com/apis/api/cloudprofiler.googleapis.com/overview?project=MY_PROJECT

![image](https://user-images.githubusercontent.com/14295804/122916102-847ffe80-d32a-11eb-8467-c47ab1b2ca76.png)

**Comment by poulad** [comment]
Issue is reproducible when using other versions such as `cloud-profiler-java-agent_20191028_RC00`.

**Comment by dadadom** [comment]
Just to be sure, did you try changing the `-cprof_service_version=0.0.1` to something else? I am not 100% sure if your problem might be related to this paragraph from [this page](https://cloud.google.com/profiler/docs/troubleshooting#missing-one-type):
> Ensure that you used a new service version after changing which profile types are collected. If you don't specify a new service version, then an existing deployment is used and the profiling agent can't transfer the data for the newly enabled profile type. For more information about deployments, see Profile collection.

**Comment by nolanmar511** [comment]
We recently had a report that the "No profiles..." message has displayed when users did not have the "Cloud Profiler User" role. https://cloud.google.com/profiler/docs/iam has the full details for querying profiles. 

While we haven't had a chance to investigate this report, it might be worthwhile to confirm that you have the correct IAM role to view profiles.

**Comment by poulad** [comment]
@nolanmar511 it worked! thank you.

Looking at the browser console when load https://console.cloud.google.com/profiler?project=MY_PROJECT page, I noticed this 403 response:

```
GET https://cloudprofiler.clients6.google.com/v2/projects/<MY_PROJECT>/profiledDeployments?endTime=2021-06-22T17:08:12.031Z&pageSize=8192&startTime=2021-06-15T17:08:12.031Z&key=<KEY>

{
  "error": {
    "code": 403,
    "message": "generic::permission_denied",
    "status": "PERMISSION_DENIED"
  }
}
```

After having my user account granted `roles/cloudprofiler.user` role, I can now see the dashboard.
