### ISSUE TITLE
Cloud Profiler + Cloud Run + Sping Boot

### ISSUE THREAD

**Issue by maciejrozanski** [GoogleCloudPlatform/cloud-profiler-java#41]
I'm trying to use Cloud Profiler with Spring Boot application on Cloud Run.
Spring Boot deployed with jib, so based on adoptopenjdk:8-jre. Latest version of Cloud Profiler lib.

Env set on Cloud Run:
> JAVA_TOOL_OPTIONS=-agentpath:/usr/lib/profiler_java_agent.so=-cprof_service=abc

I'm getting error:
> E0813 11:06:21.070848 2 throttler_api.cc:84] GRPC: src/core/lib/security/credentials/alts/check_gcp_environment.cc:60 BIOS data file cannot be opened.

No other logs.
No data is visible in Cloud Profiler console.

Any ideas how to fix?

**Comment by nolanmar511** [comment]
I'm closing this issue because Cloud Profiler doesn't support Cloud Run.
