### ISSUE TITLE
Profiler can hang the JVM when request is exited after ABORTED state

### ISSUE THREAD

**Issue by alexandru-es** [GoogleCloudPlatform/cloud-profiler-java#43]
In the 
```void APIThrottler::OnCreationError(const grpc::Status& st) {```
method, there is a sleep being set for when the retry operation should happen. When that happens, our timeout varies, but on average, it's around 38 minutes.

https://github.com/GoogleCloudPlatform/cloud-profiler-java/blob/a36b9c8b9fd3588b17d4c4a21bba54cd2ce7ede1/src/throttler_api.cc#L393

If the JVM wants to exit before that, it's kept hanging by the sleep that was set.

The throttler has a closed_ field that indicates that the jvm is shutting down, that should probably be used to determine if we still need to sleep or if we can close early to release the resources.

So instead of an uninterruptable "clock_->SleepFor 38 minutes"
There could be something that's more premissive, like
```
wait_start_time = time before wait
while (now - wait_start_time < 38 minutes AND !closed_) {
    sleep 30s
}
```
or any other interruptable timeout such that when the jvm wants to exit it doesn't have to wait for this.

The JVM shutting down signal is set here
https://github.com/GoogleCloudPlatform/cloud-profiler-java/blob/a36b9c8b9fd3588b17d4c4a21bba54cd2ce7ede1/src/entry.cc#L146

The next line stops the worker which then notifies the throttler that it's stopping but if it's stuck in the sleep cycle, it won't react to it until after it's over, preventing exit

**Comment by alexandru-es** [comment]
Here's an example of the behavior before and after this patch 
https://github.com/apixandru/cloud-profiler-java/commit/3731917b15f9e68190a2df3eda424fab5c49ba23

before (jvm hangs until sleep is over even if it's shutting down)
![throttler_now](https://user-images.githubusercontent.com/77993724/147598523-701cc617-7f83-4adc-a23b-b350b8198d5a.png)

after (sleep interrupts when the jvm is shutting down)
![throttler_died_nice](https://user-images.githubusercontent.com/77993724/147598584-d5804a7b-4f2d-40fc-9703-86cbf8138d6c.png)

**Comment by amchiclet** [comment]
Hello. Thanks for reporting and debugging this. We have a fix for this and it should be merged soon.

**Comment by amchiclet** [comment]
The latest PR includes a fix for this issue.

Exiting during the ABORTED state should not be blocking any more.
