### ISSUE TITLE
Create releases on Github

### ISSUE THREAD

**Issue by tsawada** [GoogleCloudPlatform/cloud-profiler-java#54]
It'd be great if I can subscribe to new releases and also can read changelog somewhere.

**Comment by aalexand** [comment]
The Cloud Profiler java agent can be installed as described [here](https://cloud.google.com/profiler/docs/profiling-java#installing-profiler). That uses the prebuilt version of the agent. There are no plans to publish those releases here on GitHub.

**Comment by tsawada** [comment]
Thanks for your response. I should have worded the title differently but I just want to get notified when new versions are released. It doesn't have to be binary releases on Github.
