### ISSUE TITLE
Occasional profile upload failures

### ISSUE THREAD

**Issue by bborysenko** [GoogleCloudPlatform/cloud-profiler-java#58]
Hi,

We have recently enabled Cloud Profiler for our application, and overall, it works well. However, we've experienced intermittent issues with profile uploads failing, resulting in these errors in our application logs:

```
Error on profile upload, discarding the profile
Profile bytes upload failed: 1 (Cancelled)
Profile bytes upload failed: 3 (generic::invalid_argument: invalid profile name: projects/<project_id>/profiles/611cef3e72e867ec)
Profile bytes upload failed: 4 (Deadline Exceeded)
```

Here's more information about our application and environment: Adoptium JDK17, Spring Boot 2.7.x, GKE, cloud-profiler-java-agent_20230515_RC00.

Our Cloud Monitoring alerting policy is triggered by these errors due to their `ERROR` severity. To avoid false alerts, we plan to exclude them from the policy. However, since they still create log noise, we'd like to either eliminate these errors entirely or change their severity to `WARNING`.

Please share any ideas you have that could help us debug and resolve the issue. Thank you!

**Comment by bborysenko** [comment]
I just found out that it could be a result of throttling on the Google Profiler side. If this is really the case, does it make sense to change the severity from `ERROR` to `WARNING`?

**Comment by punya** [comment]
Sorry for the delayed response @bborysenko.

I understand why this message can be confusing, because it’s a warning from the perspective of the overall functioning of Profiler. However, it correctly states that there was an error in the operation of uploading that *particular* profile.
