### ISSUE TITLE
Cloud Function support

### ISSUE THREAD

**Issue by vojkny** [GoogleCloudPlatform/cloud-profiler-java#69]
It seem Java profiler is enabled by default in App engine, but not in Cloud Functions and there is no way to enable it there.

Will it be somehow possible to use profiler within Cloud Functions as well?

**Comment by psx95** [comment]
Hi @vojkny, 

Unfortunately, Cloud Profiler is not supported in Cloud Functions. You can find a list of supported environments [here](https://cloud.google.com/profiler/docs/profiling-java).

Currently, we do not have any plans of supporting Cloud Profiler on Cloud Functions.

**Comment by vojkny** [comment]
But can you please plan this? It would make completely sense to accommodate the existing infrastructure together.

**Comment by punya** [comment]
@vojkny thanks for the feedback. Unfortunately our team doesn't have enough capacity to add this support any time soon, so it'll have to stay on the backlog.

**Comment by vojkny** [comment]
if this stays in your backlog without closing for "not planned",  I would be happy.
