### ISSUE TITLE
Source out of data (maybe?)

### ISSUE THREAD

**Issue by bboughton** [GoogleCloudPlatform/cloud-profiler-java#9]
While debugging an issue with publishing profiler data I experienced behavior from the profiler agent leads me to believe that the source code hosted here is out of date.

I was debugging an issue where the profiler returns a permission error when trying to publish data to a GCP project other then the one that the profiler is running in. I found that the latest version of the profiler has fixed the issue. However, the way credentials are retrieved seems to be different then what the source code says should be happening. In the source code the credentials are [only pulled from the metadata service](https://github.com/GoogleCloudPlatform/cloud-profiler-java/blob/master/src/cloud_env.cc#L167-L194) but I was seeing that they are also being sourced from a Service Account key file referenced in the env var **GOOGLE_APPLICATION_CREDENTIALS**.

**Comment by jqll** [comment]
The source code here uses GoogleDefaultCredentials, see [here](https://github.com/GoogleCloudPlatform/cloud-profiler-java/blob/master/src/throttler_api.cc#L107). Though it's indeed slightly out of date. We will update soon.

**Comment by bboughton** [comment]
Ahh, sorry for the false alarm then. Should I close this or do you want to leave it open as a reminder to update the source?

**Comment by jqll** [comment]
No problem! Let's leave it open as a reminder to update the source.
